const i18Obj = {
    'en': {
    'footer': '@2019 Logwork. All Right Reserved.',
    'menu_home': 'Home',
    'menu_recipes': 'Recipes',
    'menu_purchase': 'Purchase',
    'menu_contact': 'Contact',
    'menu_article': 'Article',
    'follow_us': 'Follow our @instagram_name',
    'vehicle_text': 'Vehicle',
    'title_text' : 'One of Saturn’s largest rings may be newer than anyone',
    'date_june_06': 'June 6, 2019    By Rickie Baroch    4 comments',
    'about_author': 'About the author',
    'author_name': 'Kate Willems',
    'author_title': 'Food & cooking bloger',
    'description': "Hi, I'm Sonia. Cooking is the way I express my creative side to the world. Welcome to my Kitchen Corner on…",
    'button': 'Continue Reading',
    'feat_posts': 'Featured posts',
    'cat_jeans': 'Jeans',
    'cat_sum': 'summer',
    'cat_auth': 'autumn',
    'cat_cloth': 'clothes',
    'cat_fashion': 'Fashion',
    'cat_sport': 'Sport',
    'cat_style': 'Style & clothes',
    'cat_minim': 'Minimalism',
    'B&W': 'Black & White',
    'Modern_cloth': 'Modern clothes',
    'cat_city': 'City',
    'cat_tour': 'tourism',
    'cat_photo': 'photography',
    'cat_social': 'Social media',
    'categories': 'Categories',
    'tags_title': 'Tags',
    'tags_business': 'Business',
    'tags_freelance': 'Freelance',
    'tags_money': 'Money',
    'tags_experience': 'Experience',
    'tags_lifestyle': 'Lifestyle',
    'tags_SEO': 'SEO',
    'tags_wordpress': 'Wordpress',
    'tags_marketing': 'Marketings',
    'tags_modern': 'Modern',
    'tags_success': 'Success',
    'tags_nature': 'Nature',
    'tags_UX': 'UX',
    'pag_old_post': 'OLDER POST',
    'pag_new_post': 'NEXT POST',
    },
    'ru' : {
    'footer': '@2019 Все права защищены.',
    'menu_home': 'Главная',
    'menu_recipes': 'Рецепты',
    'menu_purchase': 'Купить',
    'menu_contact': 'Контакты',
    'menu_article': 'Параграф',
    'follow_us': 'Следите за нашим @instagram_name',
    'vehicle_text': 'Vehicle',
    'title_text' : 'Одно из самых больших колец Сатурна',
    'date_june_06': '6 июня 2019    Рикки Бэроч',
    'about_author': 'О авторе',
    'author_name': 'Кэйт Виллемс',
    'author_title': 'Кулинарный блогер',
    'description': "Привет, я София. КУлинария - это путь моего самовыражения в этом мире. Добро пожаловать в закулисье...",
    'button': 'Продолжить читать',
    'feat_posts': 'Показаные посты',
    'cat_jeans': 'Джинсы',
    'cat_sum': 'Лето',
    'cat_auth': 'Осень',
    'cat_cloth': 'Одежда',
    'cat_fashion': 'Мода',
    'cat_sport': 'Спорт',
    'cat_style': 'Стиль и одежда',
    'cat_minim': 'Минимализм',
    'B&W': 'Черное & Белое',
    'Modern_cloth': 'Современная одежда',
    'cat_city': 'Город',
    'cat_tour': 'Туризм',
    'cat_photo': 'Искусство фотографии',
    'cat_social': 'Социальные сети',
    'categories': 'Категории',
    'tags_title': 'Тэги',
    'tags_business': 'Бизнес',
    'tags_freelance': 'Фриланс',
    'tags_money': 'Деньги',
    'tags_experience': 'Опыт',
    'tags_lifestyle': 'Стиль жизни',
    'tags_SEO': 'SEO',
    'tags_wordpress': 'Пресса',
    'tags_marketing': 'Маркетинг',
    'tags_modern': 'Современность',
    'tags_success': 'Успех',
    'tags_nature': 'Природа',
    'tags_UX': 'UX',
    'pag_old_post': 'СТАРЫЕ ПОСТЫ',
    'pag_new_post': 'НОВЫЕ ПОСТЫ',
    }
   };

   let lang = window.navigator.language;
   let lg = lang.substring(0, 2);
   GetTranslate(lg);

   function GetTranslate(lg){

        var obj = document.querySelectorAll('[data-i18]');
        obj.forEach(element => {
            var attr = element.getAttribute('data-i18');
            element.textContent = i18Obj[lg][attr];
        });
   }
   